### PR TITLE
chore: Add global color variables

### PR DESCRIPTION
**Pull request by daveclinton**
# Add Project Wide Variables

This change adds a new ts file containing the global color variables from the figma design

Fixes # ([issue](https://github.com/SpaceyaTech/Team-Berlin-React/issues/2))

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
 requires a documentation update

# How Has This Been Tested?
- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by jumalaw98** [comment]
Can the global variables be added in the index.css like 
```
:root{
      --color-bg: #;
    --color-bg-varian: #;
    --color-primary: #;
    --color-primary-variant: ;
    --color-white: #;
    --color-light: ;
}
```

or 
why did you make it to different file?
Enlighten me on this too

**Comment by daveclinton** [comment]
> Can the global variables be added in the index.css like
> 
> ```
> :root{
>       --color-bg: #;
>     --color-bg-varian: #;
>     --color-primary: #;
>     --color-primary-variant: ;
>     --color-white: #;
>     --color-light: ;
> }
> ```
> 
>  Save
> or why did you make it to different file? Enlighten me on this too

 In my opinion. Being able to access theme values without an import or an inline function is a breath of fresh air. You do lose some static typing benefits—more on this later—but it's a very happy tradeoff in my eyes.

**Comment by jumalaw98** [comment]
@mamba-dev-KE @beingnile  would you mind helping out on this review, the css file/ variable to use

**Comment by mamba-dev-KE** [comment]
Will have a look tomorrow

**Comment by jumalaw98** [comment]
@mamba-dev-KE keep me updated, I'll be grateful to get your feedback, on this merge

**Comment by mamba-dev-KE** [comment]
@jumalaw98 imo this would work well with a CSS In JS styling strategy using something like inline styles in .ts components or something like Styled components or emotion because importing the value in .css files would not work. What strategy do you have in mind @daveclinton ?

**Comment by jumalaw98** [comment]
@mamba-dev-KE what could be your suggestions, as we wait for same points from @daveclinton

**Comment by jumalaw98** [comment]
> @jumalaw98 imo this would work well with a CSS In JS styling strategy using something like inline styles in .ts components or something like Styled components or emotion because importing the value in .css files would not work. What strategy do you have in mind @daveclinton ?

@daveclinton whats your response on this

**Pull request merged**
