### PR TITLE
Add table of contents, about and product vision section to README #3

### LINKED ISSUE #3: Create a Better Project Readme that explains more on what the project does and how to contribute
Create A Better ReadMe Explaining What The Project Is About
The Readme should also include the [product vision](https://github.com/SpaceyaTech/Team-Berlin-React/wiki/Product-Vision---Team-Berlin) and what the product is about.

### PR DESCRIPTION
**Pull request by Clinton-dev**
# Description

Added the following sections to team-Berlin-react readme: table of content, about and product vision . Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #3 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by jumalaw98** [comment]
@daveclinton how do you see these changes on the readme.md file

**Comment by Clinton-dev** [comment]
you could check the file changed or https://github.com/Clinton-dev/Team-Berlin-React/tree/pre-dev you could check my readme

**Review by daveclinton — CHANGES_REQUESTED** [review]
@Clinton-dev you were added as a contributor for this project already which means you didn't have to fork the repo. You just needed to clone it and make changes on your own branch off the pre-dev branch.
Please add the contribution guidelines of contributors that have already been invited to contribute. Otherwise, it looks good entirely.

**Comment by Clinton-dev** [comment]
Hi @daveclinton  so what I should add is the steps that invited contributors should take?

**Review by jumalaw98 — COMMENTED** [review]
@Clinton-dev modify the contributing.md doc, i think that what @daveclinton is suggesting

**Comment by daveclinton** [comment]
Yes

**Comment by Clinton-dev** [comment]
Closed in order to follow proper work git flow

**Pull request closed without merging**
